server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888/}
  reactor:
    netty:
      http:
        server:
          access