spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/product-db
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:password}

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}

spring.kafka.producer.bootstrap-servers=localhost:9092

file.storage.path=/Users/shivrajdesale/Workspaces/app-uploads/local

application-description=Its Demo Application for practice
application-license=API Licence
application-version=1.0